# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-10 08:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.DecimalField(decimal_places=1, max_digits=4)),
                ('title', models.TextField(max_length=200)),
                ('description', models.TextField(max_length=200)),
                ('pageCount', models.IntegerField()),
                ('extension', models.TextField(default='.png')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=500)),
                ('page', models.IntegerField()),
                ('order', models.IntegerField(default=0)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComicDatabase.Chapter')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComicDatabase.Character')),
            ],
            options={
                'ordering': ['chapter', 'page', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='character',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ComicDatabase.Species'),
        ),
        migrations.AlterUniqueTogether(
            name='line',
            unique_together=set([('chapter', 'page', 'order')]),
        ),
    ]
